site_name: Flutter Jam
theme:
  name: material
  language: en
  features:
    - tabs
nav:
    - Home: index.md
    - About: about.md
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/codingjamdev
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kc_highlight
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/kyungcheol
